# docker-compose.yml

services:
  nodejs-app:
    command: node app.js
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app_container
    ports:
      - '3001:3001'
    environment:
      # URI kết nối tới MongoDB Atlas
      MONGO_URI: 'mongodb+srv://chiennth225602:aavM2vL8NVqUoD6R@cluster0.zyeqztw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
    restart: always
